--- # ansible playbook with condition
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
   - name: install apache2 in debian machine
     command: apt-get install -y apache2
     when: ansible_os_family == "Debian"
   - name: install apcahe server for Redhat machine
     command: yum install httpd -y
     when ansible_os_family == "RedHat"